### ISSUE TITLE
功能扩展

### ISSUE THREAD

**Issue by alex1528** [lijiahangmax/orion-ops#2]
1. 解决纯内网机器的运维问题;
2. 解决设备录入的问题,比如设备自动注册;

**Comment by lijiahangmax** [comment]
纯内网应该没有问题吧
机器的自动发现无法实现, 但是后续会增加导入导出功能

**Comment by alex1528** [comment]
说的是如何去管理对端是纯没网的设备，但设备可以通外网

**Comment by lijiahangmax** [comment]
这个只能支持终端 ssh 连接, 不支持其他方式以及协议, ssh 能与宿主机通信那就可以进行统一管理

**Comment by lijiahangmax** [comment]
机器录入支持模板导入了
