### ISSUE TITLE
能直接使用docker 构建吗？

### ISSUE THREAD

**Issue by badboycxcc** [lijiahangmax/orion-ops#37]
部署npm环境各种错误，想着知道docker部署开箱即用

**Comment by badboycxcc** [comment]
目前只找到这个：https://hub.docker.com/r/5idns/orion-ops/tags，不是最新版本。

**Comment by badboycxcc** [comment]
在构建前端代码出现错误

**Comment by lijiahangmax** [comment]
支持, 可以看下 docker-compose.yml
