### ISSUE TITLE
ops构建发布日志中显示脚本执行成功并成功发布，实际登录服务器查看服务没有启动

### ISSUE THREAD

**Issue by Amazing8** [lijiahangmax/orion-ops#62]
> 发布ctd - pos日志如下

![image](https://github.com/user-attachments/assets/dd560c4f-c419-4f10-922c-083e39eb722a)

实际构建成功的程序并没有启动，构建我登录服务器查看包已经更新，已经成功构建，就是最后启动不起来，之前项目是可以的，在当前这个项目不知道什么原因导致服务启动不起来，nohup，也加了sleep，尝试了这种解决方案，但是依然是一样的结果；

**Comment by lijiahangmax** [comment]
https://ops.orionsec.cn/support/faq.html#nohup-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%A0%E6%B3%95%E5%90%AF%E5%8A%A8%E7%A8%8B%E5%BA%8F

 这个参考了吗

**Comment by lijiahangmax** [comment]
是 1.3.0 版本的问题吗, 暂时先回退到 1.2.8 试试

**Comment by Amazing8** [comment]
> https://ops.orionsec.cn/support/faq.html#nohup-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%A0%E6%B3%95%E5%90%AF%E5%8A%A8%E7%A8%8B%E5%BA%8F
> 
> 这个参考了吗

这个试了，但是，还是同样的报错，回退版本还没试，但是，不是所有项目都是如此，有的项目还是可以正常部署的，个别项目不可以

**Comment by lijiahangmax** [comment]
你这个是哪个版本? 是1.3.0 吗? 1.3.0 有点问题

**Comment by Amazing8** [comment]
> 你这个是哪个版本? 是1.3.0 吗? 1.3.0 有点问题

是1.3这个版本

**Comment by lijiahangmax** [comment]
你可以先尝试切换到 1.2.8 版本, 数据库没有变化, 只有前后端换一下就可以了, 看看还有没有这个问题
