### ISSUE TITLE
能新增个角色管理的功能吗

### ISSUE THREAD

**Issue by wuqiang3424** [lijiahangmax/orion-ops#66]
能新增个角色管理的功能吗，需要给开发人员使用，权限有点儿大，没有找到角色权限设置入口

**Comment by lijiahangmax** [comment]
这个功能可以自己实现

**Comment by wuqiang3424** [comment]
是我自己写一个这个功能？

**Comment by wuqiang3424** [comment]
我觉得这个是一个挺好的项目，尤其是在cicd功能上，比目前绝大多数个人开源的项目更贴合运维方面多一些，也更接近jenkins，比起那些花里胡哨不具有实际意义的项目功能来说，这个项目是在运维技术方面是十分专业的。

**Comment by lijiahangmax** [comment]
因为是个人开发, 没有那么多的时间去维护, 手头工作很多
