### ISSUE TITLE
发布操作，写了启动多个Java程序的命令，发现最后一个Java程序总是不启动

### ISSUE THREAD

**Issue by gggyd123** [lijiahangmax/orion-ops#7]
最后在最后多写了一个echo命令才可以，最后一条命令是不是有什么特殊处理

**Comment by lijiahangmax** [comment]
springboot模板 https://lijiahangmax.gitee.io/orion-ops/#/template/java-springboot-template
需要sleep一下如:   (nohup java -jar $jarName >> run.log 2>&1 &) && sleep 1
